Public Class Form1
    Dim time As Byte = 0
    Private Sub Timer1_Tick(sender As Object, e As EventArgs) Handles Timer1.Tick
        If (time = 0) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Red
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Silver
            Panel13.BackColor = Color.Silver
            Panel14.BackColor = Color.Silver
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Red
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 1) Then
            Panel1.BackColor = Color.Silver
            Panel2.BackColor = Color.Silver
            Panel3.BackColor = Color.Silver
            Panel4.BackColor = Color.Silver
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Silver
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Silver
            Panel13.BackColor = Color.Silver
            Panel14.BackColor = Color.Silver
            Panel15.BackColor = Color.Silver
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Silver
            Panel23.BackColor = Color.Silver
            Panel24.BackColor = Color.Silver
            Panel25.BackColor = Color.Silver
            time = time + 1
        ElseIf (time = 2) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Silver
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Silver
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Red
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 3) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Silver
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 4) Then
            Panel1.BackColor = Color.Silver
            Panel2.BackColor = Color.Silver
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Silver
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Red
            Panel10.BackColor = Color.Silver
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Silver
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Silver
            Panel23.BackColor = Color.Silver
            Panel24.BackColor = Color.Silver
            Panel25.BackColor = Color.Silver
            time = time + 1
        ElseIf (time = 5) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Silver
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Red
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 6) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Silver
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Red
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Red
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 7) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Silver
            Panel11.BackColor = Color.Silver
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Silver
            Panel14.BackColor = Color.Silver
            Panel15.BackColor = Color.Silver
            Panel16.BackColor = Color.Silver
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Red
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Silver
            Panel22.BackColor = Color.Silver
            Panel23.BackColor = Color.Silver
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Silver
            time = time + 1
        ElseIf (time = 8) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Red
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Red
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Red
            Panel23.BackColor = Color.Red
            Panel24.BackColor = Color.Red
            Panel25.BackColor = Color.Red
            time = time + 1
        ElseIf (time = 9) Then
            Panel1.BackColor = Color.Red
            Panel2.BackColor = Color.Red
            Panel3.BackColor = Color.Red
            Panel4.BackColor = Color.Red
            Panel5.BackColor = Color.Red
            Panel6.BackColor = Color.Red
            Panel7.BackColor = Color.Silver
            Panel8.BackColor = Color.Silver
            Panel9.BackColor = Color.Silver
            Panel10.BackColor = Color.Red
            Panel11.BackColor = Color.Red
            Panel12.BackColor = Color.Red
            Panel13.BackColor = Color.Red
            Panel14.BackColor = Color.Red
            Panel15.BackColor = Color.Red
            Panel16.BackColor = Color.Red
            Panel17.BackColor = Color.Silver
            Panel18.BackColor = Color.Silver
            Panel19.BackColor = Color.Silver
            Panel20.BackColor = Color.Silver
            Panel21.BackColor = Color.Red
            Panel22.BackColor = Color.Silver
            Panel23.BackColor = Color.Silver
            Panel24.BackColor = Color.Silver
            Panel25.BackColor = Color.Silver
            time = 0
        End If
    End Sub

    Private Sub Form1_Load(sender As Object, e As EventArgs) Handles MyBase.Load
        Timer1.Start()
    End Sub
End Class
